### PR TITLE
fix: fix build error due to null safety error with kotlin compiler 2

### LINKED ISSUE #146: [android] RN 0.77 support
### Description
After upgrading to React Native 0.77, which introduced Kotlin compiler v2 for Android, the Didomi SDK is failing to compile due to null safety violations in Kotlin code.

### Environment
- React Native: 0.77
- Android Gradle Plugin: 8.7.2
- Gradle: 8.10.2
- Didomi React Native SDK version: 2.10.0

### Error Message

```
Android gradle plugin: 8.7.2
Gradle: 8.10.2

> Task :didomi_react-native:compileDebugKotlin FAILED
e: file:///Users/valentin/workspace/app/node_modules/@didomi/react-native/android/src/main/java/io/didomi/reactnative/DidomiModule.kt:271:21 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
e: file:///Users/valentin/workspace/app/node_modules/@didomi/react-native/android/src/main/java/io/didomi/reactnative/DidomiModule.kt:1182:51 Argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':didomi_react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

### Root Cause
The error occurs because Kotlin compiler v2 is more strict about null safety. The SDK is attempting to pass potentially nullable strings (`String?`) to methods that expect non-null strings (`String`).

### Steps to Reproduce
1. Use React Native 0.77 or higher
2. Install @didomi/react-native SDK
3. Attempt to build Android app

### Expected Behavior
The SDK should compile successfully with Kotlin compiler v2.

### Suggested Fix
The SDK needs to be updated to handle null safety properly in the affected methods at:
- DidomiModule.kt:271
- DidomiModule.kt:1182

Would you like me to create a pull request to fix these null safety issues?

### PR DESCRIPTION
**Pull request by ernoufv**
## Description
 This PR fixes Kotlin type mismatch errors by properly handling nullable strings in two functions:
 
 - `toSet()` extension function now safely handles nullable strings from ReadableArray
 - `readableArrayToStringArray` function provides empty string fallback for null values
 
 ## Related Issues
 Fixes type mismatch errors where Kotlin expects non-null String but receives String?
 
 ## Testing
 - Tested with null string values
 - Verified existing functionality remains intact

resolves #146

### CODE REVIEW

File: android/src/main/java/io/didomi/reactnative/DidomiModule.kt [hunk 1]
```diff
@@ -1179,7 +1179,7 @@ class DidomiModule(reactContext: ReactApplicationContext) : ReactContextBaseJava
 
     // Required to transform from array to variadic.
     private fun readableArrayToStringArray(readableArray: ReadableArray): Array<String> {
-        return Array(readableArray.size()) { i -> readableArray.getString(i) }
+        return Array(readableArray.size()) { i -> readableArray.getString(i) ?: "" }
```
Comment (pmerlet-at-didomi) [inline android/src/main/java/io/didomi/reactnative/DidomiModule.kt:1182]: We can avoid unnecessary values here
```suggestion
        return readableArray.toSet().toTypedArray()
```

Comment (pmerlet-at-didomi) [reply android/src/main/java/io/didomi/reactnative/DidomiModule.kt:1182]: or even
```
    private fun readableArrayToStringArray(readableArray: ReadableArray) = readableArray.toSet().toTypedArray()
```

**Review by nicolas-chaix-didomi — APPROVED** [review]

**Review by pmerlet-at-didomi — APPROVED** [review]
